version: '3.5'
services:

  go-service-example:
    build: .
    hostname: go-service-example.svc
    container_name: go-service-example.svc
    volumes:
      - .:/usr/src/go-service-example
    working_dir: /usr/src/go-service-example
    environment:
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    command: bash -c "go run cmd/go-service-example/main.go"
    ports:
      - "${API_PORT}:8081"
    depends_on:
      - postgres
    networks:
      example-network:

  postgres:
    image: postgres:13
    hostname: postgres.svc
    container_name: postgres.svc
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      example-network:

networks:
  example-network:
    driver: bridge
